---
- name: Setup Kubernetes cluster
  hosts: all
  become: yes
  vars:
    scripts_dir: scripts
    temp_dir: /tmp

  tasks:
    - name: Copy hosts file to /etc/hosts
      copy:
        src: hosts
        dest: /etc/hosts
        mode: '0644'
      tags: hosts

    - name: Copy and execute scripts
      block:
        - name: Copy {{ item }} script to remote
          copy:
            src: "{{ scripts_dir }}/{{ item }}"
            dest: "{{ temp_dir }}/{{ item }}"
            mode: '0755'
          loop:
            - disable-swap.sh
            - install-containerd.sh
            - install-kubernetes.sh
          register: script_copy

        - name: Execute disable swap script
          shell: "{{ temp_dir }}/disable-swap.sh"
          register: script_output_swap
          tags: swap

        - name: Execute containerd installation script
          shell: "{{ temp_dir }}/install-containerd.sh"
          register: script_output_containerd
          tags: containerd

        - name: Execute kubernetes installation script
          shell: "{{ temp_dir }}/install-kubernetes.sh"
          register: script_output_kubernetes
          tags: kubernetes

      rescue:
        - name: Display error message
          debug:
            msg: "An error occurred during script execution"

    - name: Display script outputs
      block:
        - name: Show swap script output
          debug:
            var: script_output_swap.stdout_lines
          when: script_output_swap.stdout_lines is defined
          tags: swap

        - name: Show containerd script output
          debug:
            var: script_output_containerd.stdout_lines
          when: script_output_containerd.stdout_lines is defined
          tags: containerd

        - name: Show containerd script errors
          debug:
            var: script_output_containerd.stderr_lines
          when: script_output_containerd.stderr_lines is defined
          tags: containerd

        - name: Show kubernetes script output
          debug:
            var: script_output_kubernetes.stdout_lines
          when: script_output_kubernetes.stdout_lines is defined
          tags: kubernetes

        - name: Show kubernetes script errors
          debug:
            var: script_output_kubernetes.stderr_lines
          when: script_output_kubernetes.stderr_lines is defined
          tags: kubernetes